[cleanup] Move _redirects from public to static
in-toto/in-toto.io pull request #51
Opened 2024-07-24 23:43 UTC by chalin

- Fixes #43
  - Moves `_redirects` from `public` to `static`
- Adjusts `layouts/partials/css.html` so that it creates a production build only in production (when `hugo.IsProduction` is true)
- Adds NPM scripts to build and serve the website. Note that these scripts aren't used by the Netlify build commands yet.

### Redirect tests

- TBC

2024-07-24 23:49 UTC, chalin commented
/cc @marcelamelara @steiza - FYI, so that you're aware that the canonical source of the _redirects file has changed.

2024-07-24 23:53 UTC, chalin commented
@DarikshaAnsari - we'll need to ensure that the `_redirects` file is also present in the Docsy-based version of the website.

2024-07-26 07:41 UTC, lukpueh reviewed
>   * Moves `_redirects` from `public` to `static`
👍 

> * Adjusts `layouts/partials/css.html` so that it creates a production build only in production (when `hugo.IsProduction` is true)

TBH, I can't tell if this is correct. Should I see a difference in the preview build? It looks like it does use the production css link (w/ hash):
```
<link rel="stylesheet" href="/css/style.94f9acd6bd00126cfa5eeb849dbf3cc631715b317a956d7516a0d3e4e1c1cef7.css" integrity="sha256-lPms1r0AEmz6XuuEnb88xjFxWzF6lW11FqDT5OHBzvc=">
```

> * Adds NPM scripts to build and serve the website. Note that these scripts aren't used by the Netlify build commands yet.

Are these commands also for devs to build locally? If so, should we update our CONTRIBUTING.md? It does not have to be part of this pr.

> * https://deploy-preview-51--in-toto.netlify.app/Statement/v0.1.0
> * https://deploy-preview-51--in-toto.netlify.app/attestation/vulns/v...

💯 for providing links here.

2024-07-26 14:25 UTC, chalin commented
> > * Adjusts `layouts/partials/css.html` so that it creates a production build only in production (when `hugo.IsProduction` is true)
> 
> TBH, I can't tell if this is correct. Should I see a difference in the preview build? It looks like it does use the production css link (w/ hash):

Right, I had not enabled the scripts for use by Netlify. I've added that change so that you can see the effect by viewing source of the preview. Let me know what you think.

> > * Adds NPM scripts to build and serve the website. Note that these scripts aren't used by the Netlify build commands yet.
> 
> Are these commands also for devs to build locally? If so, should we update our CONTRIBUTING.md? It does not have to be part of this pr.

Both for use by Netlify and devs. I've updated `CONTRIBUTING.md` too.

> > * https://deploy-preview-51--in-toto.netlify.app/Statement/v0.1.0
> > * https://deploy-preview-51--in-toto.netlify.app/attestation/vulns/v...
> 
> 💯 for providing links here.

👍🏻

2024-07-29 07:52 UTC, lukpueh requested changes

2024-07-29 07:52 UTC, lukpueh commented on package.json
> +    "make:public": "mkdir -p public && git init -b main public",
What's this command needed for?

2024-07-29 07:52 UTC, lukpueh commented on CONTRIBUTING.md
> +npm run serve
Did you try this? It fails on my machine with this error:

```
> hugo --cleanDestinationDir -e dev -DF --minify --disableFastRender serve

Error: unknown flag: --disableFastRender
```

Comparing this to the removed Makefile, it looks like it's missing the `server` subcommand.

2024-07-29 07:53 UTC, lukpueh commented
> > TBH, I can't tell if this is correct. Should I see a difference in the preview build? It looks like it does use the production css link (w/ hash):
> 
> Right, I had not enabled the scripts for use by Netlify. I've added that change so that you can see the effect by viewing source of the preview. Let me know what you think.

Looks like expected now. Thanks!

2024-07-29 12:03 UTC, chalin commented on package.json
> +    "make:public": "mkdir -p public && git init -b main public",
It creates the `public` folder and sets it up as a local git repo. This makes it easier to view generated file diff when working on website changes. It's more of a power-user feature. Would you like for me to remove it?

2024-07-29 12:04 UTC, chalin commented on CONTRIBUTING.md
> +npm run serve
Fixed. No, it was because of the wrong order of arguments.

2024-08-02 07:37 UTC, lukpueh commented on package.json
> +    "make:public": "mkdir -p public && git init -b main public",
No, it's fine.

2024-08-02 07:38 UTC, lukpueh approved these changes

2024-08-02 07:38 UTC, merged